security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            memory:
                users:
                    ducksmanager:  { password: '%env(ROLE_PASSWORD_DUCKSMANAGER)%', roles: [ 'ROLE_COLLECTION' ] }
                    whattheduck: { password: '%env(ROLE_PASSWORD_WHATTHEDUCK)%', roles: [ 'ROLE_COLLECTION' ] }
                    edgecreator: { password: '%env(ROLE_PASSWORD_EDGECREATOR)%', roles: [ 'ROLE_EDGECREATOR' ] }
                    rawsql: { password: '%env(ROLE_PASSWORD_RAWSQL)%', roles: [ 'ROLE_RAWSQL' ] }
                    admin: { password: '%env(ROLE_PASSWORD_ADMIN)%', roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(?!coa)(?!cover-id)(?!edges)(?!status).+
            http_basic: ~

    access_control:
        - { path: ^/rawsql, roles: ROLE_RAWSQL }
        - { path: ^/ducksmanager/resetDemo, roles: ROLE_ADMIN }
        - { path: ^/edgesprites/, roles: ROLE_ADMIN }
        - { path: ^/notifications/, roles: ROLE_ADMIN }
        - { path: ^/collection/, roles: ROLE_COLLECTION }
        - { path: ^/edgecreator/, roles: ROLE_EDGECREATOR }
