FROM php:7.1-apache
MAINTAINER Bruno Perel

COPY .htaccess /var/www/html/dm-server/.htaccess
COPY docker-compose.yml /var/www/html/dm-server/docker-compose.yml
COPY app /var/www/html/dm-server/app
COPY assets /var/www/html/dm-server/assets
COPY scripts /var/www/html/dm-server/scripts
COPY index.php /var/www/html/dm-server/index.php
COPY composer.json /var/www/html/dm-server/composer.json

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y git wget unzip mariadb-client nano ssmtp

RUN echo 'sendmail_path = "/usr/sbin/ssmtp -t"' > /usr/local/etc/php/conf.d/mail.ini

RUN pecl install xdebug-2.5.5

RUN yes '' | pecl install channel://pecl.php.net/apcu_bc-1.0.4
RUN echo 'extension=apcu.so' > /usr/local/etc/php/conf.d/apcu.ini

RUN docker-php-ext-install -j$(nproc) pdo pdo_mysql exif opcache && docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN cd /var/www/html/dm-server && \
  composer install --no-plugins --no-scripts && \
  touch development.log && chown www-data:www-data development.log && \
  touch pimple.json && chown www-data:www-data pimple.json && \
  chmod +x scripts/*
