version: '2.4'
services:
  web-api:
    container_name: dm-server-web-dev
    image: "nginx:1.15"
    ports:
     - "10002:80"
    depends_on:
     - php
    restart: always
    volumes:
     - .:/var/www/html:z
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
     - front-network

  php:
    container_name: dm-server-php-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    depends_on:
      - db
      - mailcatcher
    volumes:
     - .:/var/www/html
     - ./php.xdebug.ini:/usr/local/etc/php/php.ini:z
    networks:
     - front-network
     - mail-network
     - db-network
     - cover-id-network
    command: sh -c 'composer install --no-plugins --no-scripts && php-fpm'

  mailcatcher:
    container_name: mailcatcher
    image: yappabe/mailcatcher
    restart: always
    ports:
      - "1080:1080"
    networks:
      - mail-network

  db:
    container_name: db
    image: "mariadb:10.4"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - $MYSQL_INIT_SCRIPT:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
      - "64999:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
      - db-network
      - cover-id-network

  coa-updater:
    container_name: coa-updater
    image: bperel/coa-updater
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: coa
      MYSQL_DATABASE_NEW: coa_new
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - db-network

  pastec:
    container_name: pastec
    image: "bperel/pastec-ubuntu-1704-timestamps"
    restart: always
    command: "./pastec -p 4212 -i /pastec-index-last.dat /pastec/data/visualWordsORB.dat"
    networks:
     - cover-id-network
    volumes:
     - $PASTEC_INIT_INDEX:/pastec-index-last.dat:ro

  duck-estimator:
    container_name: duck-estimator
    image: "mcr.microsoft.com/playwright:focal"
    depends_on:
     - db
    environment:
     - MYSQL_COA_HOST=db
     - MYSQL_COA_PORT=3306
     - MYSQL_COA_DATABASE=coa
     - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
     - GITHUB_TOKEN=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
     - GITHUB_NAME=Admin
     - GITHUB_EMAIL=admin@ducksmanager.net
    networks:
     - db-network
    volumes:
     - duck_estimator_cache:/home/cache
     - node_cache:/root/.cache
    command: "bash -c 'git clone --depth 1 --single-branch https://github.com/bperel/duck-estimator && cd duck-estimator && npm install && node duck-estimator.js --cache-dir=/home/cache'"

networks:
  front-network:
    driver: bridge
  mail-network:
    driver: bridge
  db-network:
    driver: bridge
  cover-id-network:
    driver: bridge

volumes:
  db:
  duck_estimator_cache:
  node_cache:
