version: '2.4'

services:
  web-api:
    container_name: dm-server-web
    image: "nginx:1.15"
    restart: always
    depends_on:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./current:/var/www:z
    networks:
      front-network:
        aliases:
          - web
      public-network:
        aliases:
          - web-api

  php:
    container_name: dm-server-php
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./msmtp.conf:/etc/msmtprc
      - ./current:/var/www:z
    networks:
      - front-network
      - db-network
      - cover-id-network


  db:
    container_name: db
    image: "mariadb:10.7"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - $MYSQL_INIT_SCRIPT:/docker-entrypoint-initdb.d/$MYSQL_INIT_SCRIPT_TARGET_FILE_NAME:ro
    ports:
      - "64999:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    networks:
      - db-network
      - cover-id-network

  pastec:
    container_name: pastec-ubuntu-1704-timestamps
    restart: always
    image: "bperel/pastec-ubuntu-1704-timestamps"
    volumes:
      - ./pastec-index-last.dat:/pastec-index-last.dat:ro
    command: "./pastec -p 4212 -i /pastec-index-last.dat /pastec/data/visualWordsORB.dat"
    networks:
      - cover-id-network

  subscription-runner:
    container_name: subscriptions-runner
    image: "library/debian:jessie-slim"
    depends_on:
      - db
    env_file: .env.prod.local
    environment:
      - MYSQL_COA_HOST=db
      - MYSQL_COA_DATABASE=coa
      - MYSQL_DM_HOST=db
      - MYSQL_DM_DATABASE=dm
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
      - db-network
    volumes:
      - ./scripts:/home/scripts
    command: "bash -c 'apt-get update && apt-get install -y mysql-client && sh /home/scripts/subscriptions/create-issues-from-subscriptions.sh'"

networks:
  front-network:
    driver: bridge
  db-network:
    driver: bridge
  cover-id-network:
    driver: bridge
  public-network:
    external: true

volumes:
  db:
  duck_estimator_cache:
  node_cache:
