FROM php:7.3-fpm
MAINTAINER Bruno Perel

RUN apt-get update && apt-get install -y git wget unzip mariadb-client nano ssmtp telnet

RUN echo 'sendmail_path = /usr/bin/env catchmail -f admin@ducksmanager.net' > /usr/local/etc/php/conf.d/mail.ini

RUN pecl install apcu
RUN echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini

RUN docker-php-ext-install -j$(nproc) pdo_mysql exif opcache

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install xdebug-2.7.0 && docker-php-ext-enable xdebug
