name: notification-sender

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
jobs:
  notification-sender:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run notification-sender
        env:
          NOTIFICATIONS_BASIC_AUTH: ${{ secrets.PRODUCTION_NOTIFICATIONS_BASIC_AUTH }}
        run: >
          ssh production "curl --request POST \
                            --url https://api.ducksmanager.net/notification/send \
                            --header \"Authorization: Basic $NOTIFICATIONS_BASIC_AUTH\" \
                            --header \"cache-control: no-cache\" \
                            --header \"x-dm-version: 1.0.0\""
