name: popularity-updater

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  popularity-updater:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}

      - name: Run popularity-updater
        run: >
          ssh production 'cd workspace/dm-server && \
                          docker compose exec -T db mysql -uroot -pchangeme dm -e "CALL reset_issue_popularities"'
